#!/usr/bin/env bash
# Upload PXT token icon to IPFS (Pinata) and record TOKEN_ICON_URI.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck disable=SC1091
source "$ROOT/scripts/token-metadata/load-env.sh"

META_DIR="$ROOT/packages/token-metadata"
ICON="${ICON:-$META_DIR/icon/pxt-128.png}"
[[ -f "$ICON" ]] || ICON="$META_DIR/icon/pxt.png"
[[ -f "$ICON" ]] || { echo "Missing icon at $META_DIR/icon/pxt.png" >&2; exit 1; }

chmod +x "$ROOT/scripts/token-metadata/pinata-upload.sh"
URI="$("$ROOT/scripts/token-metadata/pinata-upload.sh" "$ICON" "pxt-token-icon.png")"

{
  echo "# Generated by make deploy-token-icon — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "TOKEN_ICON_URI=$URI"
} > "$META_DIR/deployed.env"

echo "TOKEN_ICON_URI=$URI"
echo "Wrote $META_DIR/deployed.env"
