#!/usr/bin/env bash
# Prepare PXT metadata/tokenlist, upload icon (if needed) + JSON to IPFS, rewrite logoURI.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck disable=SC1091
source "$ROOT/scripts/token-metadata/load-env.sh"

META_DIR="$ROOT/packages/token-metadata"
OUT_DIR="$META_DIR/out"
CLUSTER="${CLUSTER:-arbitrum}"

chmod +x \
  "$ROOT/scripts/token-metadata/prepare.sh" \
  "$ROOT/scripts/token-metadata/deploy-icon.sh" \
  "$ROOT/scripts/token-metadata/pinata-upload.sh"

GATEWAY="${PINATA_GATEWAY:-https://ipfs.io/ipfs}"
GATEWAY="${GATEWAY%/}"

# Rewrite https://…/ipfs/<cid> to $GATEWAY/<cid> (same CID, public host).
_rewrite_gateway_uri() {
  local uri="${1:-}"
  [[ -n "$uri" ]] || return 0
  local cid="${uri##*/}"
  [[ "$cid" =~ ^(Qm[1-9A-HJ-NP-Za-km-z]{44}|bafy[a-z0-9]+)$ ]] || {
    echo "$uri"
    return 0
  }
  echo "${GATEWAY}/${cid}"
}

if [[ -f "$META_DIR/deployed.env" ]]; then
  # shellcheck disable=SC1090
  set -a && . "$META_DIR/deployed.env" && set +a
fi
if [[ -z "${TOKEN_ICON_URI:-}" ]]; then
  echo "No TOKEN_ICON_URI yet — uploading icon…"
  "$ROOT/scripts/token-metadata/deploy-icon.sh"
  # shellcheck disable=SC1090
  set -a && . "$META_DIR/deployed.env" && set +a
else
  TOKEN_ICON_URI="$(_rewrite_gateway_uri "$TOKEN_ICON_URI")"
  export TOKEN_ICON_URI
  echo "Reusing icon CID via $TOKEN_ICON_URI"
fi

IMAGE_URI="$TOKEN_ICON_URI" CLUSTER="$CLUSTER" \
  bash "$ROOT/scripts/token-metadata/prepare.sh"

META_URI="$("$ROOT/scripts/token-metadata/pinata-upload.sh" \
  "$OUT_DIR/metadata.json" "pxt-metadata.json")"
LIST_URI="$("$ROOT/scripts/token-metadata/pinata-upload.sh" \
  "$OUT_DIR/pxt.tokenlist.json" "pxt.tokenlist.json")"

{
  echo "# Generated by make deploy-token-metadata — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "TOKEN_ICON_URI=$TOKEN_ICON_URI"
  echo "TOKEN_METADATA_URI=$META_URI"
  echo "TOKEN_LIST_URI=$LIST_URI"
  echo "TOKEN_CLUSTER=$CLUSTER"
} > "$META_DIR/deployed.env"

cat <<EOF
Deployed Phoenix token metadata ($CLUSTER)

  Icon:     $TOKEN_ICON_URI
  Metadata: $META_URI
  Tokenlist:$LIST_URI

Import the tokenlist URL in Uniswap / wallets, or add token manually with:
  logoURI = $TOKEN_ICON_URI

Recorded in packages/token-metadata/deployed.env
EOF
