#!/usr/bin/env bash
# Parse `make launch` forge logs and merge deployed addresses into evm/.env.$(CLUSTER).
# Usage: write-launch-env.sh <forge-log> <evm-env-file>
set -euo pipefail

LOG="${1:?usage: write-launch-env.sh <forge-log> <evm-env-file>}"
EVM_OUT="${2:?missing evm env path}"

PERMIT2="0x000000000022D473030F116dDEE9F6B43aC78BA3"

# Preserve secrets / RPC / launch config from existing env if present.
PRIVATE_KEY=""
RPC_URL=""
ANVIL_RPC_URL=""
ARBITRUM_RPC_URL=""
BASE_RPC_URL=""
ARBISCAN_API_KEY=""
BASESCAN_API_KEY=""
ETHERSCAN_API_KEY=""
FORK_CHAIN_ID=""
LAUNCH_SALT=""
LAUNCH_OWNER=""
RECIPIENT_APPROVER=""
BUYBACK_CALLERS=""
FEE_EXEMPT_WALLETS=""
NO_PENALTY_WALLETS=""
LP_SEED_USDC_WHOLE="20"
LP_SEED_PXT_WHOLE="20000"
POOL_MANAGER=""
POSITION_MANAGER=""
UNIVERSAL_ROUTER=""
STATE_VIEW=""
QUOTER=""
BUYBACK_RECYCLE_WIDTH_SPACINGS="10"
BUYBACK_MAX_SLIPPAGE_BPS="200"
EVM_CLUSTER=""
if [[ -f "$EVM_OUT" ]]; then
  # shellcheck disable=SC1090
  set -a && . "$EVM_OUT" && set +a || true
fi

pick() {
  local key="$1"
  awk -v k="$key" '
    /^== Logs ==/ { inlogs=1; next }
    inlogs && /^## / { exit }
    inlogs && index($0, "  " k ": ") == 1 {
      sub(/^  [^:]+: /, "")
      print
      exit
    }
  ' "$LOG"
}

PXT="$(pick PXT)"
USDC="$(pick USDC)"
if [[ -z "$USDC" ]]; then USDC="$(pick mUSDC)"; fi
HOOK="$(pick PhoenixV4ReturnDeltaHook)"
COLLECTOR="$(pick PhoenixFeeCollector)"
DONATION="$(pick 'Donation wallet')"
MARKETING="$(pick 'Marketing wallet')"
ADMIN="$(pick Admin)"
CURRENCY0="$(pick currency0)"
CURRENCY1="$(pick currency1)"
ANTI_BOT="$(pick 'Anti-bot seller')"
ANTI_BOT_OPERATOR="$(pick 'Anti-bot operator (funds open)')"
SELL_UNLOCK="$(pick 'Sell unlock timestamp')"
OPEN_SELL="$(pick PhoenixAntiBotOpenSell)"
SWAP_TEST="$(pick PoolSwapTest)"
SWAP_TEST="${SWAP_TEST:-${POOL_SWAP_TEST:-}}"
PM_FROM_LOG="$(pick PoolManager)"
LAUNCHER="$(pick PhoenixLauncher)"
ORCH="$(pick PhoenixOrchestrator)"
PXT_DEPLOYER="$(pick PhoenixPxtDeployer)"
HOOK_DEPLOYER="$(pick PhoenixHookDeployer)"
COLLECTOR_DEPLOYER="$(pick PhoenixCollectorDeployer)"
OPEN_SELL_DEPLOYER="$(pick PhoenixOpenSellDeployer)"

REQUIRED=(PXT USDC HOOK DONATION MARKETING ADMIN CURRENCY0 CURRENCY1 COLLECTOR OPEN_SELL SWAP_TEST LAUNCHER ORCH)
for v in "${REQUIRED[@]}"; do
  if [[ -z "${!v}" ]]; then
    echo "write-launch-env: missing ${v} in forge log" >&2
    exit 1
  fi
done

POOL_MANAGER="${PM_FROM_LOG:-${POOL_MANAGER:-}}"
RPC_URL="${RPC_URL:-${ANVIL_RPC_URL:-${ARBITRUM_RPC_URL:-${BASE_RPC_URL:-}}}}"
CLUSTER_NAME="${EVM_CLUSTER:-}"
if [[ -z "$CLUSTER_NAME" ]]; then
  CLUSTER_NAME="$(basename "$EVM_OUT")"
  CLUSTER_NAME="${CLUSTER_NAME#.env.}"
fi

cat >"$EVM_OUT" <<EOF
# Auto-updated by make launch — DO NOT COMMIT
EVM_CLUSTER=${CLUSTER_NAME}
HOOK_MODE=return-delta
RPC_URL=${RPC_URL}
${ANVIL_RPC_URL:+ANVIL_RPC_URL=${ANVIL_RPC_URL}}
${ARBITRUM_RPC_URL:+ARBITRUM_RPC_URL=${ARBITRUM_RPC_URL}}
${BASE_RPC_URL:+BASE_RPC_URL=${BASE_RPC_URL}}
FORK_CHAIN_ID=${FORK_CHAIN_ID}
${ARBISCAN_API_KEY:+ARBISCAN_API_KEY=${ARBISCAN_API_KEY}}
${BASESCAN_API_KEY:+BASESCAN_API_KEY=${BASESCAN_API_KEY}}
${ETHERSCAN_API_KEY:+ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}}

PRIVATE_KEY=${PRIVATE_KEY}
ADMIN_ADDRESS=${ADMIN}
DONATION_WALLET=${DONATION}
MARKETING_WALLET=${MARKETING}
${LAUNCH_OWNER:+LAUNCH_OWNER=${LAUNCH_OWNER}}
${LAUNCH_SALT:+LAUNCH_SALT=${LAUNCH_SALT}}
${RECIPIENT_APPROVER:+RECIPIENT_APPROVER=${RECIPIENT_APPROVER}}
${BUYBACK_CALLERS:+BUYBACK_CALLERS=${BUYBACK_CALLERS}}
${FEE_EXEMPT_WALLETS:+FEE_EXEMPT_WALLETS=${FEE_EXEMPT_WALLETS}}
${NO_PENALTY_WALLETS:+NO_PENALTY_WALLETS=${NO_PENALTY_WALLETS}}

PXT_ADDRESS=${PXT}
QUOTE_TOKEN_ADDRESS=${USDC}
PHOENIX_HOOK=${HOOK}
FEE_COLLECTOR=${COLLECTOR}
PHOENIX_LAUNCHER=${LAUNCHER}
PHOENIX_ORCHESTRATOR=${ORCH}
${PXT_DEPLOYER:+PHOENIX_PXT_DEPLOYER=${PXT_DEPLOYER}}
${HOOK_DEPLOYER:+PHOENIX_HOOK_DEPLOYER=${HOOK_DEPLOYER}}
${COLLECTOR_DEPLOYER:+PHOENIX_COLLECTOR_DEPLOYER=${COLLECTOR_DEPLOYER}}
${OPEN_SELL_DEPLOYER:+PHOENIX_OPEN_SELL_DEPLOYER=${OPEN_SELL_DEPLOYER}}
POOL_CURRENCY0=${CURRENCY0}
POOL_CURRENCY1=${CURRENCY1}
POOL_FEE=0
POOL_TICK_SPACING=60
POOL_MANAGER=${POOL_MANAGER}
POSITION_MANAGER=${POSITION_MANAGER}
UNIVERSAL_ROUTER=${UNIVERSAL_ROUTER}
STATE_VIEW=${STATE_VIEW}
QUOTER=${QUOTER}
POOL_SWAP_TEST=${SWAP_TEST}
PERMIT2=${PERMIT2}
ANTI_BOT_SELLER=${ANTI_BOT:-$ADMIN}
ANTI_BOT_OPERATOR=${ANTI_BOT_OPERATOR:-$ADMIN}
OPEN_SELL_OPERATOR=${ANTI_BOT_OPERATOR:-$ADMIN}
ANTI_BOT_OPEN_SELL=${OPEN_SELL}
SELL_UNLOCK_TIMESTAMP=${SELL_UNLOCK}

USE_MOCK_USDC=${USE_MOCK_USDC:-false}
QUOTE_DECIMALS=6
LP_SEED_USDC_WHOLE=${LP_SEED_USDC_WHOLE}
LP_SEED_PXT_WHOLE=${LP_SEED_PXT_WHOLE}
BUYBACK_RECYCLE_WIDTH_SPACINGS=${BUYBACK_RECYCLE_WIDTH_SPACINGS}
BUYBACK_MAX_SLIPPAGE_BPS=${BUYBACK_MAX_SLIPPAGE_BPS}
EOF
chmod 600 "$EVM_OUT"
echo "Wrote $EVM_OUT"
