#!/usr/bin/env bash
# Parse forge ceremony logs and merge addresses into evm/.env.$(CLUSTER).
# Supports Phase 1 (CreateToken — partial) and Phase 2 (DeployPool — full stack).
# Usage: write-launch-env.sh <forge-log> <evm-env-file>
set -euo pipefail

LOG="${1:?usage: write-launch-env.sh <forge-log> <evm-env-file>}"
EVM_OUT="${2:?missing evm env path}"

PERMIT2="0x000000000022D473030F116dDEE9F6B43aC78BA3"

# Preserve secrets / RPC / launch config from existing env if present.
PRIVATE_KEY=""
RPC_URL=""
ANVIL_RPC_URL=""
ARBITRUM_RPC_URL=""
BASE_RPC_URL=""
ARBISCAN_API_KEY=""
BASESCAN_API_KEY=""
ETHERSCAN_API_KEY=""
FORK_CHAIN_ID=""
LAUNCH_SALT=""
LAUNCH_OWNER=""
RECIPIENT_APPROVER=""
BUYBACK_CALLERS=""
FEE_EXEMPT_WALLETS=""
NO_PENALTY_WALLETS=""
LP_SEED_USDC_WHOLE="20"
LP_SEED_PXT_WHOLE="20000"
POOL_MANAGER=""
POSITION_MANAGER=""
UNIVERSAL_ROUTER=""
STATE_VIEW=""
QUOTER=""
BUYBACK_RECYCLE_WIDTH_SPACINGS="10"
BUYBACK_MAX_SLIPPAGE_BPS="200"
EVM_CLUSTER=""
PXT_ADDRESS=""
QUOTE_TOKEN_ADDRESS=""
PHOENIX_HOOK=""
FEE_COLLECTOR=""
PHOENIX_LAUNCHER=""
PHOENIX_ORCHESTRATOR=""
POOL_CURRENCY0=""
POOL_CURRENCY1=""
POOL_SWAP_TEST=""
ANTI_BOT_OPEN_SELL=""
ANTI_BOT_SELLER=""
ANTI_BOT_OPERATOR=""
OPEN_SELL_OPERATOR=""
SELL_UNLOCK_TIMESTAMP=""
DONATION_WALLET=""
MARKETING_WALLET=""
ADMIN_ADDRESS=""
USE_MOCK_USDC=""
if [[ -f "$EVM_OUT" ]]; then
  # shellcheck disable=SC1090
  set -a && . "$EVM_OUT" && set +a || true
fi

pick() {
  local key="$1"
  awk -v k="$key" '
    /^== Logs ==/ { inlogs=1; next }
    inlogs && /^## / { exit }
    inlogs && index($0, "  " k ": ") == 1 {
      sub(/^  [^:]+: /, "")
      print
      exit
    }
  ' "$LOG"
}

PXT="$(pick PXT)"
USDC="$(pick USDC)"
if [[ -z "$USDC" ]]; then USDC="$(pick mUSDC)"; fi
HOOK="$(pick PhoenixV4ReturnDeltaHook)"
COLLECTOR="$(pick PhoenixFeeCollector)"
DONATION="$(pick 'Donation wallet')"
MARKETING="$(pick 'Marketing wallet')"
ADMIN="$(pick Admin)"
CURRENCY0="$(pick currency0)"
CURRENCY1="$(pick currency1)"
ANTI_BOT="$(pick 'Anti-bot seller')"
ANTI_BOT_OPERATOR_LOG="$(pick 'Anti-bot operator (funds open)')"
SELL_UNLOCK="$(pick 'Sell unlock timestamp')"
OPEN_SELL="$(pick PhoenixAntiBotOpenSell)"
SWAP_TEST="$(pick PoolSwapTest)"
SWAP_TEST="${SWAP_TEST:-${POOL_SWAP_TEST:-}}"
PM_FROM_LOG="$(pick PoolManager)"
LAUNCHER="$(pick PhoenixLauncher)"
ORCH="$(pick PhoenixOrchestrator)"
PXT_DEPLOYER="$(pick PhoenixPxtDeployer)"
HOOK_DEPLOYER="$(pick PhoenixHookDeployer)"
COLLECTOR_DEPLOYER="$(pick PhoenixCollectorDeployer)"
OPEN_SELL_DEPLOYER="$(pick PhoenixOpenSellDeployer)"

# Merge log → env (prefer log when present).
[[ -n "$PXT" ]] && PXT_ADDRESS="$PXT"
[[ -n "$USDC" ]] && QUOTE_TOKEN_ADDRESS="$USDC"
[[ -n "$HOOK" ]] && PHOENIX_HOOK="$HOOK"
[[ -n "$COLLECTOR" ]] && FEE_COLLECTOR="$COLLECTOR"
[[ -n "$DONATION" ]] && DONATION_WALLET="$DONATION"
[[ -n "$MARKETING" ]] && MARKETING_WALLET="$MARKETING"
[[ -n "$ADMIN" ]] && ADMIN_ADDRESS="$ADMIN"
[[ -n "$CURRENCY0" ]] && POOL_CURRENCY0="$CURRENCY0"
[[ -n "$CURRENCY1" ]] && POOL_CURRENCY1="$CURRENCY1"
[[ -n "$ANTI_BOT" ]] && ANTI_BOT_SELLER="$ANTI_BOT"
[[ -n "$ANTI_BOT_OPERATOR_LOG" ]] && ANTI_BOT_OPERATOR="$ANTI_BOT_OPERATOR_LOG"
[[ -n "$ANTI_BOT_OPERATOR_LOG" ]] && OPEN_SELL_OPERATOR="$ANTI_BOT_OPERATOR_LOG"
[[ -n "$SELL_UNLOCK" ]] && SELL_UNLOCK_TIMESTAMP="$SELL_UNLOCK"
[[ -n "$OPEN_SELL" ]] && ANTI_BOT_OPEN_SELL="$OPEN_SELL"
[[ -n "$SWAP_TEST" ]] && POOL_SWAP_TEST="$SWAP_TEST"
[[ -n "$LAUNCHER" ]] && PHOENIX_LAUNCHER="$LAUNCHER"
[[ -n "$ORCH" ]] && PHOENIX_ORCHESTRATOR="$ORCH"
POOL_MANAGER="${PM_FROM_LOG:-${POOL_MANAGER:-}}"

PHASE1_REQUIRED=(PXT_ADDRESS ADMIN_ADDRESS DONATION_WALLET MARKETING_WALLET PHOENIX_LAUNCHER PHOENIX_ORCHESTRATOR)
for v in "${PHASE1_REQUIRED[@]}"; do
  if [[ -z "${!v}" ]]; then
    echo "write-launch-env: missing ${v} (need Phase 1 CreateToken log fields)" >&2
    exit 1
  fi
done

# Phase 2 extras when hook appears in this log (or already in env from prior deploy-pool).
HAS_POOL=0
if [[ -n "${PHOENIX_HOOK:-}" && -n "${FEE_COLLECTOR:-}" && -n "${ANTI_BOT_OPEN_SELL:-}" ]]; then
  HAS_POOL=1
  if [[ -z "${QUOTE_TOKEN_ADDRESS:-}" ]]; then
    echo "write-launch-env: QUOTE_TOKEN_ADDRESS missing after DeployPool" >&2
    exit 1
  fi
  if [[ -z "${POOL_CURRENCY0:-}" || -z "${POOL_CURRENCY1:-}" ]]; then
    echo "write-launch-env: currency0/currency1 missing after DeployPool" >&2
    exit 1
  fi
  if [[ -z "${POOL_SWAP_TEST:-}" ]]; then
    echo "write-launch-env: PoolSwapTest missing after DeployPool" >&2
    exit 1
  fi
fi

RPC_URL="${RPC_URL:-${ANVIL_RPC_URL:-${ARBITRUM_RPC_URL:-${BASE_RPC_URL:-}}}}"
CLUSTER_NAME="${EVM_CLUSTER:-}"
if [[ -z "$CLUSTER_NAME" ]]; then
  CLUSTER_NAME="$(basename "$EVM_OUT")"
  CLUSTER_NAME="${CLUSTER_NAME#.env.}"
fi

cat >"$EVM_OUT" <<EOF
# Auto-updated by make create-token / deploy-pool — DO NOT COMMIT
EVM_CLUSTER=${CLUSTER_NAME}
HOOK_MODE=return-delta
RPC_URL=${RPC_URL}
${ANVIL_RPC_URL:+ANVIL_RPC_URL=${ANVIL_RPC_URL}}
${ARBITRUM_RPC_URL:+ARBITRUM_RPC_URL=${ARBITRUM_RPC_URL}}
${BASE_RPC_URL:+BASE_RPC_URL=${BASE_RPC_URL}}
FORK_CHAIN_ID=${FORK_CHAIN_ID}
${ARBISCAN_API_KEY:+ARBISCAN_API_KEY=${ARBISCAN_API_KEY}}
${BASESCAN_API_KEY:+BASESCAN_API_KEY=${BASESCAN_API_KEY}}
${ETHERSCAN_API_KEY:+ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}}

PRIVATE_KEY=${PRIVATE_KEY}
ADMIN_ADDRESS=${ADMIN_ADDRESS}
DONATION_WALLET=${DONATION_WALLET}
MARKETING_WALLET=${MARKETING_WALLET}
${LAUNCH_OWNER:+LAUNCH_OWNER=${LAUNCH_OWNER}}
${LAUNCH_SALT:+LAUNCH_SALT=${LAUNCH_SALT}}
${RECIPIENT_APPROVER:+RECIPIENT_APPROVER=${RECIPIENT_APPROVER}}
${BUYBACK_CALLERS:+BUYBACK_CALLERS=${BUYBACK_CALLERS}}
${FEE_EXEMPT_WALLETS:+FEE_EXEMPT_WALLETS=${FEE_EXEMPT_WALLETS}}
${NO_PENALTY_WALLETS:+NO_PENALTY_WALLETS=${NO_PENALTY_WALLETS}}

PXT_ADDRESS=${PXT_ADDRESS}
${QUOTE_TOKEN_ADDRESS:+QUOTE_TOKEN_ADDRESS=${QUOTE_TOKEN_ADDRESS}}
${PHOENIX_HOOK:+PHOENIX_HOOK=${PHOENIX_HOOK}}
${FEE_COLLECTOR:+FEE_COLLECTOR=${FEE_COLLECTOR}}
PHOENIX_LAUNCHER=${PHOENIX_LAUNCHER}
PHOENIX_ORCHESTRATOR=${PHOENIX_ORCHESTRATOR}
${PXT_DEPLOYER:+PHOENIX_PXT_DEPLOYER=${PXT_DEPLOYER}}
${HOOK_DEPLOYER:+PHOENIX_HOOK_DEPLOYER=${HOOK_DEPLOYER}}
${COLLECTOR_DEPLOYER:+PHOENIX_COLLECTOR_DEPLOYER=${COLLECTOR_DEPLOYER}}
${OPEN_SELL_DEPLOYER:+PHOENIX_OPEN_SELL_DEPLOYER=${OPEN_SELL_DEPLOYER}}
${POOL_CURRENCY0:+POOL_CURRENCY0=${POOL_CURRENCY0}}
${POOL_CURRENCY1:+POOL_CURRENCY1=${POOL_CURRENCY1}}
POOL_FEE=0
POOL_TICK_SPACING=60
${POOL_MANAGER:+POOL_MANAGER=${POOL_MANAGER}}
${POSITION_MANAGER:+POSITION_MANAGER=${POSITION_MANAGER}}
${UNIVERSAL_ROUTER:+UNIVERSAL_ROUTER=${UNIVERSAL_ROUTER}}
${STATE_VIEW:+STATE_VIEW=${STATE_VIEW}}
${QUOTER:+QUOTER=${QUOTER}}
${POOL_SWAP_TEST:+POOL_SWAP_TEST=${POOL_SWAP_TEST}}
PERMIT2=${PERMIT2}
${ANTI_BOT_SELLER:+ANTI_BOT_SELLER=${ANTI_BOT_SELLER}}
${ANTI_BOT_OPERATOR:+ANTI_BOT_OPERATOR=${ANTI_BOT_OPERATOR}}
${OPEN_SELL_OPERATOR:+OPEN_SELL_OPERATOR=${OPEN_SELL_OPERATOR}}
${ANTI_BOT_OPEN_SELL:+ANTI_BOT_OPEN_SELL=${ANTI_BOT_OPEN_SELL}}
${SELL_UNLOCK_TIMESTAMP:+SELL_UNLOCK_TIMESTAMP=${SELL_UNLOCK_TIMESTAMP}}

USE_MOCK_USDC=${USE_MOCK_USDC:-false}
QUOTE_DECIMALS=6
LP_SEED_USDC_WHOLE=${LP_SEED_USDC_WHOLE}
LP_SEED_PXT_WHOLE=${LP_SEED_PXT_WHOLE}
BUYBACK_RECYCLE_WIDTH_SPACINGS=${BUYBACK_RECYCLE_WIDTH_SPACINGS}
BUYBACK_MAX_SLIPPAGE_BPS=${BUYBACK_MAX_SLIPPAGE_BPS}
EOF
chmod 600 "$EVM_OUT"
if [[ "$HAS_POOL" -eq 1 ]]; then
  echo "Wrote $EVM_OUT (phase 2 stack)"
else
  echo "Wrote $EVM_OUT (phase 1 token — run make deploy-pool next)"
fi
